# Generated by Django 3.2.4 on 2021-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='lastname',
        ),
    ]
