# Generated by Django 3.2.4 on 2021-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210811_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Address',
            new_name='address',
        ),
    ]
