# Generated by Django 3.2.4 on 2021-08-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_address_agent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='contact',
            field=models.IntegerField(blank=True, default='9856895426'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
