# Generated by Django 3.2.4 on 2021-08-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210813_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='contact',
        ),
    ]
