# Generated by Django 3.2.4 on 2021-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_agent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='contact',
            field=models.IntegerField(default=9856587895),
            preserve_default=False,
        ),
    ]
