# Generated by Django 3.2.4 on 2021-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Donor_name', models.CharField(max_length=20)),
                ('DateOfCollectingFood', models.DateField()),
                ('TimeOfCollectingFood', models.TimeField()),
                ('Quantity', models.CharField(max_length=50)),
                ('Orphanage_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
